import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import 'market_price_helpers.dart';
import 'report_section.dart';

/// Builds and hands off real PDF reports for the admin dashboard — the
/// system's only "export" used to be a CSV string copied to the clipboard.
/// Generation (pdf package) and delivery (printing package's native share
/// sheet — save to Files, email, etc.) are kept separate so a report can be
/// generated once and either shared or, later, previewed/printed.
class PdfReportService {
  static const _brandGreen = PdfColor.fromInt(0xFF1B5E20);

  static pw.Widget _header(String title, String subtitle, {String? generatedByLine}) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text('AgriTrade+',
            style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold, color: _brandGreen)),
        pw.SizedBox(height: 6),
        pw.Text(title, style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 2),
        pw.Text(subtitle, style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
        pw.SizedBox(height: 4),
        pw.Text(
          generatedByLine ??
              'Generated ${DateFormat('MMM d, y \'at\' h:mm a').format(DateTime.now())}',
          style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey500),
        ),
        pw.Divider(height: 20, color: PdfColors.grey300),
      ],
    );
  }

  static pw.Widget _table(List<String> headers, List<List<String>> rows) {
    if (rows.isEmpty) {
      return pw.Text('No data for this period.',
          style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600));
    }
    return pw.TableHelper.fromTextArray(
      headers: headers,
      data: rows,
      headerStyle: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, color: PdfColors.white),
      headerDecoration: const pw.BoxDecoration(color: _brandGreen),
      cellStyle: const pw.TextStyle(fontSize: 10),
      cellAlignment: pw.Alignment.centerLeft,
      cellHeight: 24,
      border: null,
      rowDecoration: const pw.BoxDecoration(
        border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey300, width: 0.5)),
      ),
    );
  }

  /// The Demand Heatmap screen's report: completed-order demand grouped
  /// by buyer location, plus the top buyer search terms — the same two
  /// datasets the old CSV export covered, now as an actual PDF.
  static Future<Uint8List> buildDemandReport({
    required List<({String barangay, int orderCount, num revenue})> demand,
    required List<MapEntry<String, int>> topSearches,
    String? periodLabel,
  }) async {
    final doc = pw.Document();
    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) => [
          _header(
            'Market Demand Report',
            periodLabel == null
                ? 'Completed orders by buyer location'
                : 'Completed orders by buyer location — $periodLabel',
          ),
          pw.Text('Demand by Area', style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          _table(
            ['Area', 'Completed Orders', 'Revenue'],
            demand.map((d) => [d.barangay, '${d.orderCount}', formatPeso(d.revenue)]).toList(),
          ),
          pw.SizedBox(height: 24),
          pw.Text('Top Buyer Searches', style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          _table(
            ['Search Term', 'Count'],
            topSearches.map((e) => [e.key, '${e.value}']).toList(),
          ),
        ],
      ),
    );
    return doc.save();
  }

  /// The Export Report dialog's PDF output — every selected Analytics
  /// Dashboard section, in dashboard order, built from the exact same
  /// DashboardAnalyticsService numbers shown on screen (see
  /// ReportExportService, which assembles [sections] and [chartImages]).
  /// A section with no [chartImages] entry (PNG capture unavailable, or
  /// the section isn't chart-backed) always falls back to its data table;
  /// [includeDataTables] additionally shows the table *under* a captured
  /// chart image too.
  static Future<Uint8List> buildFullDashboardReport({
    required String title,
    required String adminName,
    required DateTime generatedAt,
    required String dateRangeLabel,
    String? notes,
    required bool landscape,
    required bool includeDataTables,
    required List<ReportSection> sections,
    Map<String, Uint8List> chartImages = const {},
  }) async {
    final doc = pw.Document();
    final generatedByLine =
        'Generated by $adminName on ${DateFormat('MMM d, y \'at\' h:mm a').format(generatedAt)}';

    final widgets = <pw.Widget>[
      _header(title, dateRangeLabel, generatedByLine: generatedByLine),
    ];

    if (notes != null && notes.trim().isNotEmpty) {
      widgets.addAll([
        pw.Text('Notes', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 4),
        pw.Text(notes.trim(), style: const pw.TextStyle(fontSize: 10)),
        pw.SizedBox(height: 20),
      ]);
    }

    for (final section in sections) {
      widgets.add(pw.Text(section.title, style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold)));
      widgets.add(pw.SizedBox(height: 8));

      final image = chartImages[section.title];
      if (image != null) {
        widgets.add(pw.Image(pw.MemoryImage(image), height: 220, fit: pw.BoxFit.contain));
        widgets.add(pw.SizedBox(height: 12));
      }
      if (image == null || includeDataTables) {
        widgets.add(_table(
          section.headers,
          section.rows.map((r) => r.map((cell) => cell?.toString() ?? '').toList()).toList(),
        ));
      }
      widgets.add(pw.SizedBox(height: 24));
    }

    doc.addPage(
      pw.MultiPage(
        pageFormat: landscape ? PdfPageFormat.a4.landscape : PdfPageFormat.a4,
        footer: (context) => pw.Container(
          alignment: pw.Alignment.centerRight,
          margin: const pw.EdgeInsets.only(top: 8),
          child: pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey500),
          ),
        ),
        build: (context) => widgets,
      ),
    );
    return doc.save();
  }

  /// The Audit Log screen's export — whatever page of entries is currently
  /// loaded/filtered on screen (not the whole collection; see
  /// AuditLogView's pagination), one row per entry.
  static Future<Uint8List> buildAuditLogReport({
    required List<({String when, String admin, String action, String details, String device, String location})>
        entries,
  }) async {
    final doc = pw.Document();
    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4.landscape,
        build: (context) => [
          _header('Admin Portal Audit Log', '${entries.length} entr${entries.length == 1 ? 'y' : 'ies'}'),
          _table(
            ['Date & Time', 'Admin', 'Action', 'Details', 'Device/Browser', 'Location/IP'],
            entries.map((e) => [e.when, e.admin, e.action, e.details, e.device, e.location]).toList(),
          ),
        ],
      ),
    );
    return doc.save();
  }

  /// The Farmer List screen's export — the KPI totals shown above the
  /// table (org-wide, not affected by filters) plus the table exactly as
  /// currently filtered/sorted on screen (see FarmerListView._export).
  static Future<Uint8List> buildFarmerListReport({
    required int totalFarmers,
    required int activeListingsTotal,
    required int completedOrdersTotal,
    required List<
        ({
          String farmerId,
          String fullName,
          String email,
          String barangay,
          String municipality,
          String dateApproved,
          int activeListings,
          int completedOrders,
        })> rows,
  }) async {
    final doc = pw.Document();
    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4.landscape,
        build: (context) => [
          _header('Farmer List Report', '${rows.length} of $totalFarmers approved farmers shown'),
          _table(
            ['Metric', 'Value'],
            [
              ['Total Farmers', '$totalFarmers'],
              ['Active Listings', '$activeListingsTotal'],
              ['Completed Orders', '$completedOrdersTotal'],
            ],
          ),
          pw.SizedBox(height: 20),
          _table(
            [
              'Farmer ID',
              'Full Name',
              'Email',
              'Barangay',
              'Municipality',
              'Date Approved',
              'Active Listings',
              'Completed Orders',
            ],
            rows
                .map((r) => [
                      r.farmerId,
                      r.fullName,
                      r.email,
                      r.barangay,
                      r.municipality,
                      r.dateApproved,
                      '${r.activeListings}',
                      '${r.completedOrders}',
                    ])
                .toList(),
          ),
        ],
      ),
    );
    return doc.save();
  }

  /// Hands the generated PDF to the OS share sheet — save to Files, email,
  /// send via chat, etc. No storage permission needed since nothing is
  /// written to app-external storage directly.
  static Future<void> share(Uint8List bytes, String filename) {
    return Printing.sharePdf(bytes: bytes, filename: filename);
  }
}
